CREATE TABLE Movies (
id_movie INT NOT NULL AUTO_INCREMENT PRIMARY KEY UNIQUE,
born YEAR NOT NULL,
country CHAR(2) NOT NULL,
name VARCHAR(20) NOT NULL,
duration SMALLINT NOT NULL,
rating SMALLINT NOT NULL
);
CREATE TABLE Cinemas (
id_cinema INT  NOT NULL AUTO_INCREMENT PRIMARY KEY UNIQUE,
name VARCHAR(20) NOT NULL,
city VARCHAR(20) NOT NULL,
address VARCHAR(256) NOT NULL,
phone VARCHAR(12) NOT NULL
);
CREATE TABLE Sessions (
id_session INT NOT NULL AUTO_INCREMENT PRIMARY KEY UNIQUE,
id_cinema INT NOT NULL,
FOREIGN KEY (id_cinema) REFERENCES Cinemas(id_cinema)
);